name: zoo_zimba
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  get: ^4.6.5
  get_storage: ^2.0.3
  firebase_auth: ^4.1.1
  firebase_messaging: ^14.0.4
  firebase_database: ^10.0.4
  flutter_local_notifications: ^12.0.2
  http: ^0.13.5
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  flutter_fortune_wheel: ^1.2.0
  device_info_plus: ^8.0.0
  device_information: ^0.0.4
  flutter_device_identifier: ^0.0.1
  sms_autofill: ^2.2.0
  audioplayers: ^1.1.1
  animated_text_kit: ^4.2.2
  animated_styled_widget: ^0.4.6
  bordered_text: ^2.0.0
  video_player: ^2.4.10
  lottie: ^2.1.0
  easy_upi_payment: ^0.1.2
  sizer: ^2.0.15
  simple_gradient_text: ^1.2.4
  webview_flutter: ^4.0.1
  url_launcher: ^6.1.7
  share_plus: ^6.3.0
  google_sign_in: ^5.4.3
  package_info_plus: ^3.0.2
  # upi_pay: ^1.0.1
  # upi_pay:
  #   git:
  #     url: https://github.com/akash0245/upi_pay.git
  #     ref: main
  # add_to_cart_animation: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/icons/
   - assets/audios/
   - assets/wheel_parts_trans/
   - assets/bet_items/
   - assets/record_items/
   - assets/ribbin_items/
   - assets/lottie_jsons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # example:
  fonts:
    - family: Canterbury
      fonts:
        - asset: assets/Canterbury.ttf

    - family: Horizon
      fonts:
        - asset: assets/Horizon.otf      
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
